1. public class TryCatch {
	public static void main(String[] args) {
		try {
			int data1 = 50/0;
		}
		catch(Exception e) {
			int data2 = 50/0;
		}
		System.out.println("rest of the code");
		}
}

Output:
ArithmeticException: / by zero

2. public class TryCatchProg {  
     
    public static void main(String args[])  
    {  
        try {  
    
            try {  
    
                    int arr[] = { 1, 2, 3, 4 };  
  
                    System.out.println(arr[10]);  
                }  
    
                catch (ArithmeticException e) {  
                    System.out.println("Arithmetic exception");  
                    System.out.println(" inner try block 2");  
                }  
            }  
    
            
            catch (ArithmeticException e) {  
                System.out.println("Arithmetic exception");  
                System.out.println("inner try block 1");  
            }  
        }  
    
        catch (ArrayIndexOutOfBoundsException e4) {  
            System.out.print(e4);  
            System.out.println(" outer (main) try block");  
        }  
        catch (Exception e5) {  
            System.out.print("Exception");  
            System.out.println(" handled in main try-block");  
        }  
    }  
}

Output:
compilation error